# -*- coding: utf-8 -*-
"""Segmented_CLV_Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x-bhEs2Y_VvMRhxw5tiF6-87i8vwQ-p2
"""
# ==========================================
# CUSTOMER INTELLIGENCE ML PLATFORM (PRODUCTION PIPELINE)
# EPIC 1 & 2: DATA ENGINEERING & PIPELINE EXPORT
# ==========================================

import polars as pl
import pandas as pd
import numpy as np
import os
import joblib
import json
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
from google.colab import drive

# ---------------------------------------------------------
# 1. MOUNT & DIRECTORY SETUP
# ---------------------------------------------------------
drive.mount('/content/drive')
base_path = "/content/drive/MyDrive/bank_churn_dataset/"
artifact_path = os.path.join(base_path, "artifacts/")
os.makedirs(artifact_path, exist_ok=True)

print("INITIALIZING PRODUCTION PIPELINE...")

# ---------------------------------------------------------
# 2. DATA PIPELINE (POLARS LAZY EXECUTION)
# ---------------------------------------------------------
print("📡 Scanning and Engineering 15M+ Transaction Logs...")

q_trans = pl.scan_csv(base_path + "transactions_data.csv").with_columns([
    pl.col("amount").str.replace_all(r"[\$,]", "").cast(pl.Float32),
    pl.col("date").str.to_datetime("%Y-%m-%d %H:%M:%S", strict=False)
])

q_users = pl.scan_csv(base_path + "users_data.csv").with_columns([
    pl.col("yearly_income").str.replace_all(r"[\$,]", "").cast(pl.Float32),
    pl.col("total_debt").str.replace_all(r"[\$,]", "").cast(pl.Float32)
]).drop(["address", "latitude", "longitude", "birth_year", "birth_month"])

q_cards = pl.scan_csv(base_path + "cards_data.csv").with_columns([
    pl.col("credit_limit").str.replace_all(r"[\$,]", "").cast(pl.Float32)
]).group_by("client_id").agg([
    pl.sum("credit_limit").alias("total_credit_limit")
])

q_cust = q_trans.group_by("client_id").agg([
    pl.count("amount").cast(pl.Int32).alias("num_transactions"),
    pl.sum("amount").alias("total_spent"),
    pl.mean("amount").alias("avg_transaction"),
    pl.max("date").alias("last_transaction"),
    pl.min("date").alias("first_transaction")
]).with_columns([
    (pl.col("last_transaction") - pl.col("first_transaction")).dt.total_days().alias("account_lifespan_days")
]).with_columns([
    # EPIC 1.2 FIX: Enforced floor to prevent division-by-zero crashes
    (pl.col("account_lifespan_days") / pl.max_horizontal(pl.col("num_transactions") - 1, 1)).alias("avg_days_between_txns")
])

q_final = q_cust.join(q_users, left_on="client_id", right_on="id", how="left") \
                .join(q_cards, on="client_id", how="left")

print("⏳ Executing Query Plan to RAM...")
final_df = q_final.collect()
df_ml = final_df.to_pandas()

# ---------------------------------------------------------
# 3. BEHAVIORAL SEGMENTATION (K-MEANS)
# ---------------------------------------------------------
print("Deploying K-Means Routing Engine...")
segment_features = ['total_spent', 'num_transactions', 'avg_days_between_txns', 'total_credit_limit']

# EPIC 1.3 FIX: Median Imputation (Removing the toxic fillna(0))
X_segment = df_ml[segment_features].copy()
X_segment.fillna(X_segment.median(), inplace=True)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_segment)

kmeans = KMeans(n_clusters=4, random_state=42, n_init=20)
df_ml['Cluster'] = kmeans.fit_predict(X_scaled)

# ---------------------------------------------------------
# 4. FRAUD DETECTION (ISOLATION FOREST)
# ---------------------------------------------------------
print("Training Multi-Dimensional Fraud Engine...")

# EPIC 1.4 & 1.1 FIX: Join behavioral context and sample randomly (Not chronologically)
q_fraud = pl.scan_csv(base_path + "transactions_data.csv").select([
    "client_id", "amount"
]).with_columns([
    pl.col("amount").str.replace_all(r"[\$,]", "").cast(pl.Float32)
]).drop_nulls()

q_fraud_enriched = q_fraud.join(q_cust.select(["client_id", "avg_transaction", "avg_days_between_txns"]), on="client_id", how="left")

# Random 30% sample captures yearly seasonality
df_fraud_pl = q_fraud_enriched.collect().sample(fraction=0.3, seed=42)
df_fraud = df_fraud_pl.to_pandas()

# Fill missing context securely before Isolation Forest
fraud_features = ['amount', 'avg_transaction', 'avg_days_between_txns']
df_fraud[fraud_features] = df_fraud[fraud_features].fillna(df_fraud[fraud_features].median())

iso_forest = IsolationForest(n_estimators=100, contamination=0.01, random_state=42, n_jobs=-1)
df_fraud['anomaly'] = iso_forest.fit_predict(df_fraud[fraud_features])

# ---------------------------------------------------------
# 5. CLV FORECASTING (XGBOOST SPECIALIST AGENTS)
# ---------------------------------------------------------
print("Training Specialist XGBoost Agents...")

clv_features = [
    'yearly_income', 'total_debt', 'credit_score', 'total_credit_limit', 'current_age',
    'num_transactions', 'avg_days_between_txns', 'account_lifespan_days'
]

clv_specialist_agents_models = {}

for cluster_id in sorted(df_ml['Cluster'].unique()):
    segment_df = df_ml[df_ml['Cluster'] == cluster_id].copy()
    
    # XGBoost handles NaNs natively, no imputation needed
    X_seg = segment_df[clv_features]
    y_seg = segment_df['total_spent']
    
    # Train Agent
    model_s = xgb.XGBRegressor(n_estimators=150, learning_rate=0.05, max_depth=3, random_state=42)
    model_s.fit(X_seg, y_seg)
    
    clv_specialist_agents_models[cluster_id] = model_s

# ---------------------------------------------------------
# 6. ARCHITECTURAL DECOUPLING & ARTIFACT EXPORT
# ---------------------------------------------------------
print("Exporting Production Artifacts to /artifacts/ ...")

# A. Dynamic Persona Mapping
centroids = kmeans.cluster_centers_
spend_centroids = centroids[:, 0]
sorted_cluster_ids = np.argsort(spend_centroids)

labels = [
    "Low Activity Account",
    "Mass Market Customer",
    "Affluent Credit Customer",
    "High-Value Client"
]
persona_map = {int(cluster_id): labels[i] for i, cluster_id in enumerate(sorted_cluster_ids)}

with open(artifact_path + 'persona_map.json', 'w') as f:
    json.dump(persona_map, f)

# B. Save Scikit-Learn Pipeline
joblib.dump(kmeans, artifact_path + 'kmeans_segmenter.pkl')
joblib.dump(scaler, artifact_path + 'feature_scaler.pkl')

# C. Save XGBoost Agents
for cluster_id, model in clv_specialist_agents_models.items():
    joblib.dump(model, artifact_path + f'clv_agent_{cluster_id}.pkl')

print("✅ EPIC 1 & 2 COMPLETE. ALL ARTIFACTS SYNCED SUCCESSFULLY.")
